# Generated by Django 6.0.2 on 2026-02-26 14:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generic_name', models.CharField(db_index=True, max_length=255, verbose_name='通用名称')),
                ('trade_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='商品名称')),
                ('related_diseases', models.TextField(blank=True, null=True, verbose_name='相关疾病')),
                ('description', models.TextField(blank=True, null=True, verbose_name='性状')),
                ('ingredients', models.TextField(blank=True, null=True, verbose_name='主要成份')),
                ('indications', models.TextField(blank=True, null=True, verbose_name='适应症')),
                ('specification', models.TextField(blank=True, null=True, verbose_name='规格')),
                ('adverse_reactions', models.TextField(blank=True, null=True, verbose_name='不良反应')),
                ('dosage', models.TextField(blank=True, null=True, verbose_name='用法用量')),
                ('contraindications', models.TextField(blank=True, null=True, verbose_name='禁忌')),
                ('precautions', models.TextField(blank=True, null=True, verbose_name='注意事项')),
                ('pregnancy_lactation_use', models.TextField(blank=True, null=True, verbose_name='孕妇及哺乳期妇女用药')),
                ('pediatric_use', models.TextField(blank=True, null=True, verbose_name='儿童用药')),
                ('geriatric_use', models.TextField(blank=True, null=True, verbose_name='老人用药')),
                ('interactions', models.TextField(blank=True, null=True, verbose_name='药物相互作用')),
                ('pharmacology_toxicology', models.TextField(blank=True, null=True, verbose_name='药理毒理')),
                ('pharmacokinetics', models.TextField(blank=True, null=True, verbose_name='药代动力学')),
                ('storage', models.TextField(blank=True, null=True, verbose_name='贮藏')),
                ('validity', models.TextField(blank=True, null=True, verbose_name='有效期')),
            ],
        ),
    ]
