# Generated by Django 6.0.2 on 2026-02-27 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstitutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_reverse_scoring', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('constitution_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.constitutiontype')),
            ],
        ),
    ]
