# Generated by Django 6.0.2 on 2026-02-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_constitutiontype_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='gender_limit',
            field=models.CharField(choices=[('M', '限男性'), ('F', '限女性'), ('N', '通用')], default='N', max_length=1),
        ),
    ]
