# Generated by Django 6.0.2 on 2026-02-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_question_gender_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='constitution',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='当前体质'),
        ),
    ]
