# Generated by Django 6.0.2 on 2026-03-02 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_constitution'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcupointFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('cn_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='功能名称')),
            ],
        ),
        migrations.CreateModel(
            name='AcupointPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('cn_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='位置名称')),
            ],
        ),
        migrations.CreateModel(
            name='Meridian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('cn_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='经络名称')),
            ],
        ),
        migrations.CreateModel(
            name='Acupoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=16, null=True)),
                ('pinyin', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('cn_name', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='穴位名称')),
                ('position', models.TextField(blank=True, null=True)),
                ('cn_position', models.TextField(blank=True, null=True, verbose_name='位置')),
                ('indication', models.TextField(blank=True, null=True)),
                ('cn_indication', models.TextField(blank=True, null=True, verbose_name='主治')),
                ('compatibility', models.TextField(blank=True, null=True)),
                ('cn_compatibility', models.TextField(blank=True, null=True, verbose_name='配伍')),
                ('acupuncture', models.TextField(blank=True, null=True)),
                ('cn_acupuncture', models.TextField(blank=True, null=True, verbose_name='针灸法')),
                ('function_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acupoints', to='core.acupointfunction')),
                ('position_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acupoints', to='core.acupointposition')),
                ('meridian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acupoints', to='core.meridian')),
            ],
        ),
    ]
